"""Paper Generator: assembles selected questions into the school's section
format (Section A/B/C/D/E...), producing the structured GeneratedPaper the
Flutter review screen renders and the PDF exporter formats.
"""
from __future__ import annotations

from datetime import datetime, timezone

from .schemas import (
    Blueprint,
    GeneratedPaper,
    GeneratedQuestionSchema,
    GeneratedSectionSchema,
    PaperMetadataSchema,
    QuestionSchema,
)
from .templates import default_sections


def generate_paper(*, paper_id: str, assessment_id: str, assessment_title: str,
                    subject: str, grade: int, blueprint: Blueprint,
                    selected_questions: list[QuestionSchema]) -> GeneratedPaper:
    sections_bp = blueprint.sections or default_sections(blueprint.total_marks)
    by_marks: dict[int, list[QuestionSchema]] = {}
    for q in selected_questions:
        by_marks.setdefault(q.marks, []).append(q)

    gen_sections: list[GeneratedSectionSchema] = []
    display_no = 1
    answer_key: dict[str, str] = {}

    for section in sections_bp:
        bucket = by_marks.get(section.marks_per_question, [])
        take = bucket[: section.question_count]
        del bucket[: section.question_count]

        gen_questions: list[GeneratedQuestionSchema] = []
        for q in take:
            gen_questions.append(GeneratedQuestionSchema(
                question_id=q.id,
                display_number=display_no,
                stem=q.stem,
                marks=q.marks,
                bloom_level=q.bloom_level,
                difficulty=q.difficulty,
            ))
            answer_key[str(display_no)] = q.answer_scheme.model_answer or "(model answer pending)"
            display_no += 1

        gen_sections.append(GeneratedSectionSchema(
            section_id=section.id,
            label=section.label,
            name=section.name,
            questions=gen_questions,
            total_marks=sum(q.marks for q in gen_questions),
        ))

    formatted = _render_text(assessment_title, subject, grade, blueprint, gen_sections)

    return GeneratedPaper(
        id=paper_id,
        assessment_id=assessment_id,
        sections=gen_sections,
        formatted_content=formatted,
        answer_key=answer_key,
        metadata=PaperMetadataSchema(
            assessment_title=assessment_title,
            subject=subject,
            grade=grade,
            total_marks=blueprint.total_marks,
            duration_minutes=blueprint.duration_minutes,
            generated_at=datetime.now(timezone.utc),
        ),
    )


def _render_text(title: str, subject: str, grade: int, blueprint: Blueprint,
                  sections: list[GeneratedSectionSchema]) -> str:
    lines = [
        title, f"Subject: {subject}    Grade: {grade}",
        f"Time Allowed: {blueprint.duration_minutes} minutes    Maximum Marks: {blueprint.total_marks}",
        "General Instructions: This paper is machine-generated by AssessmentOS and pending teacher review.",
        "",
    ]
    for section in sections:
        lines.append(f"SECTION {section.label} — {section.name} ({section.total_marks} marks)")
        for gq in section.questions:
            lines.append(f"{gq.display_number}. {gq.stem}  [{gq.marks}]")
        lines.append("")
    return "\n".join(lines)
